"""
report_integrity.py — WEEKLY "Data Integrity Check" (internal).
Thin wrapper: runs the existing integrity_audit.py, then files its output into
the standard reports/ folder shape (report.md + data.csv + latest/). The audit
stays the single source of truth; this only relocates and tabulates it so the
integrity report lives alongside the client reports with the same convention.
"""

import json
import subprocess
import pandas as pd
import report_lib as R


def run():
    # Run the audit. It exits non-zero when a CRITICAL exists — that's fine here;
    # we still want to file the report. Capture rather than propagate.
    subprocess.run(["python", "integrity_audit.py"], check=False)

    rep = R.Report(
        slug="data-integrity",
        title="Khabar — Data Integrity Check",
        cadence="weekly",
        subtitle="Weekly · internal · full audit output filed for history",
    )

    try:
        data = json.load(open("integrity_report.json"))
    except FileNotFoundError:
        rep.gap("Integrity audit", "integrity_report.json not produced")
        rep.write(); return

    tables = pd.DataFrame(data.get("tables", []))
    if not tables.empty:
        crit = tables[tables["flags"].apply(
            lambda fs: any(f[0] == "CRITICAL" for f in fs))]
        rep.action(f"{len(crit)} CRITICAL, "
                   f"{len(tables)-len(crit)} clean/warn across "
                   f"{len(tables)} output tables.",
                   priority=1)
        for _, r in crit.iterrows():
            for lvl, msg in r["flags"]:
                if lvl == "CRITICAL":
                    rep.action(f"`{r['table']}` — {msg}", priority=1)
        # flatten to a CSV the same way the client tables do
        flat = tables[["table", "level", "rows", "distinct_dates",
                       "brands", "max_date", "score"]].copy()
        rep.save_csv(flat)

        rep.h2("Per-table health")
        flat_sorted = flat.sort_values("score", ascending=False)
        rep.table(flat_sorted, headers=["Table", "Level", "Rows", "Dates",
                                        "Brands", "Max date", "Score"])

    inv = data.get("substrate", {}).get("invariants", {})
    if inv:
        rep.h2("Invariants")
        for k, v in inv.items():
            rep.p(f"- {k}: **{v}**")

    rep.note("Generated by integrity_audit.py; see integrity_report.md for the full run.")
    rep.write()


if __name__ == "__main__":
    run()
